name: custom_marker_icon_2
description: A package to use local image, network image and icons as google_maps_flutter's marker icon.
version: 0.2.0
repository: https://github.com/abhishekduhoon/custom_marker_icon
issue_tracker: https://github.com/abhishekduhoon/custom_marker_icon/issues

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  google_maps_flutter: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
# flutter:
